# Generated by Django 5.2.6 on 2025-11-03 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userstockposition',
            name='app_usersto_user_id_746c1e_idx',
        ),
        migrations.RemoveIndex(
            model_name='userstockposition',
            name='app_usersto_stock_i_7dcb76_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userstockposition',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userstockposition',
            name='admin_profit_loss',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Admin sets custom profit/loss value', max_digits=20),
        ),
        migrations.AddField(
            model_name='userstockposition',
            name='admin_profit_loss_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Admin sets custom profit/loss percentage', max_digits=8),
        ),
        migrations.AddField(
            model_name='userstockposition',
            name='use_admin_profit',
            field=models.BooleanField(default=False, help_text='Use admin-set profit instead of calculated profit'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='change_percent',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market_cap',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(choices=[('AAPL', 'Apple Inc. (AAPL)'), ('MSFT', 'Microsoft Corporation (MSFT)'), ('GOOGL', 'Alphabet Inc. (GOOGL)'), ('GOOG', 'Alphabet Inc. Class C (GOOG)'), ('AMZN', 'Amazon.com Inc. (AMZN)'), ('META', 'Meta Platforms Inc. (META)'), ('TSLA', 'Tesla Inc. (TSLA)'), ('NVDA', 'NVIDIA Corporation (NVDA)'), ('AMD', 'Advanced Micro Devices (AMD)'), ('INTC', 'Intel Corporation (INTC)'), ('NFLX', 'Netflix Inc. (NFLX)'), ('DIS', 'Walt Disney Company (DIS)'), ('SPOT', 'Spotify Technology (SPOT)'), ('ROKU', 'Roku Inc. (ROKU)'), ('V', 'Visa Inc. (V)'), ('MA', 'Mastercard Inc. (MA)'), ('PYPL', 'PayPal Holdings (PYPL)'), ('SQ', 'Block Inc. (SQ)'), ('COIN', 'Coinbase Global (COIN)'), ('SOFI', 'SoFi Technologies (SOFI)'), ('AFRM', 'Affirm Holdings (AFRM)'), ('MARA', 'Marathon Digital Holdings (MARA)'), ('RIOT', 'Riot Platforms Inc. (RIOT)'), ('CLSK', 'CleanSpark Inc. (CLSK)'), ('MSTR', 'MicroStrategy Inc. (MSTR)'), ('SHOP', 'Shopify Inc. (SHOP)'), ('ABNB', 'Airbnb Inc. (ABNB)'), ('UBER', 'Uber Technologies (UBER)'), ('DASH', 'DoorDash Inc. (DASH)'), ('AVGO', 'Broadcom Inc. (AVGO)'), ('QCOM', 'QUALCOMM Inc. (QCOM)'), ('MU', 'Micron Technology (MU)'), ('ASML', 'ASML Holding (ASML)'), ('CRM', 'Salesforce Inc. (CRM)'), ('ORCL', 'Oracle Corporation (ORCL)'), ('ADBE', 'Adobe Inc. (ADBE)'), ('NOW', 'ServiceNow Inc. (NOW)'), ('SNOW', 'Snowflake Inc. (SNOW)'), ('CRWD', 'CrowdStrike Holdings (CRWD)'), ('ZS', 'Zscaler Inc. (ZS)'), ('ENPH', 'Enphase Energy (ENPH)'), ('SEDG', 'SolarEdge Technologies (SEDG)'), ('RUN', 'Sunrun Inc. (RUN)'), ('SNAP', 'Snap Inc. (SNAP)'), ('PINS', 'Pinterest Inc. (PINS)'), ('TWLO', 'Twilio Inc. (TWLO)'), ('BMR', 'Beamr Imaging Ltd. (BMR)'), ('ZM', 'Zoom Video Communications (ZM)'), ('DOCU', 'DocuSign Inc. (DOCU)')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstockposition',
            name='average_buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='userstockposition',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstockposition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userstockposition',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userstockposition',
            name='shares',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userstockposition',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='app.stock'),
        ),
        migrations.AlterField(
            model_name='userstockposition',
            name='total_invested',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userstockposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_positions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userstockposition',
            index=models.Index(fields=['user', 'stock', 'is_active'], name='app_usersto_user_id_ec1fb6_idx'),
        ),
    ]
