# Generated by Django 5.2.6 on 2025-11-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='next_amount_to_upgrade',
            field=models.DecimalField(decimal_places=2, default=5000.0, help_text='Total bonus earned from referrals', max_digits=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='current_loyalty_status',
            field=models.CharField(choices=[('iron', 'Iron'), ('silver', 'Silver'), ('gold', 'Gold')], default='iron', help_text='Current loyalty tier', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='next_loyalty_status',
            field=models.CharField(choices=[('iron', 'Iron'), ('silver', 'Silver'), ('gold', 'Gold')], default='silver', help_text='Next loyalty tier', max_length=20),
        ),
    ]
