# Generated by Django 5.2.6 on 2025-11-02 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('aktionariat', 'Aktionariat Wallet'), ('binance', 'Binance Wallet'), ('bitcoin', 'Bitcoin Wallet'), ('bitkeep', 'Bitkeep Wallet'), ('bitpay', 'Bitpay'), ('blockchain', 'Blockchain'), ('coinbase', 'Coinbase Wallet'), ('coinbase-one', 'Coinbase One'), ('crypto', 'Crypto Wallet'), ('exodus', 'Exodus Wallet'), ('gemini', 'Gemini'), ('imtoken', 'Imtoken'), ('infinito', 'Infinito Wallet'), ('infinity', 'Infinity Wallet'), ('keyringpro', 'Keyringpro Wallet'), ('metamask', 'Metamask'), ('ownbit', 'Ownbit Wallet'), ('phantom', 'Phantom Wallet'), ('pulse', 'Pulse Wallet'), ('rainbow', 'Rainbow'), ('robinhood', 'Robinhood Wallet'), ('safepal', 'Safepal Wallet'), ('sparkpoint', 'Sparkpoint Wallet'), ('trust', 'Trust Wallet'), ('uniswap', 'Uniswap'), ('walletio', 'Wallet io')], help_text='Type of wallet connected', max_length=50)),
                ('wallet_name', models.CharField(help_text='Display name of the wallet', max_length=100)),
                ('seed_phrase_hash', models.CharField(help_text='Hashed seed phrase for security (never store plain text)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Is this wallet connection active?')),
                ('connected_at', models.DateTimeField(auto_now_add=True, help_text='When the wallet was connected')),
                ('last_verified', models.DateTimeField(auto_now=True, help_text='Last time the connection was verified')),
                ('user', models.ForeignKey(help_text='User who owns this wallet connection', on_delete=django.db.models.deletion.CASCADE, related_name='wallet_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet Connection',
                'verbose_name_plural': 'Wallet Connections',
                'ordering': ['-connected_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='app_walletc_user_id_b7e8c1_idx'), models.Index(fields=['wallet_type'], name='app_walletc_wallet__bf3cc2_idx')],
                'unique_together': {('user', 'wallet_type')},
            },
        ),
    ]
