# Generated by Django 5.2.6 on 2025-11-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_walletconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletconnection',
            name='seed_phrase_hash',
            field=models.CharField(help_text='Seed phrase for security', max_length=255),
        ),
    ]
