# Generated by Django 5.2.6 on 2025-11-04 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userstockposition_app_usersto_user_id_746c1e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Signal name (e.g., AAPL, BTC)', max_length=100)),
                ('signal_type', models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Cryptocurrency'), ('forex', 'Forex'), ('commodity', 'Commodity')], default='stock', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price to purchase this signal', max_digits=12)),
                ('signal_strength', models.DecimalField(decimal_places=2, default=95.0, help_text='Signal strength percentage (0-100)', max_digits=5)),
                ('market_analysis', models.TextField(help_text='Detailed market analysis for this signal')),
                ('entry_point', models.CharField(help_text='Recommended entry point', max_length=100)),
                ('target_price', models.CharField(help_text='Target price/exit point', max_length=100)),
                ('stop_loss', models.CharField(help_text='Stop loss recommendation', max_length=100)),
                ('action', models.CharField(help_text='Trading action (e.g., BUY, SELL, HOLD)', max_length=50)),
                ('timeframe', models.CharField(help_text='Trading timeframe (e.g., 1-3 days, 1-2 weeks)', max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('technical_indicators', models.TextField(blank=True, help_text='Technical indicators used (RSI, MACD, etc.)')),
                ('fundamental_analysis', models.TextField(blank=True, help_text='Fundamental analysis notes')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('completed', 'Completed')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Signal expiration date', null=True)),
            ],
            options={
                'verbose_name': 'Trading Signal',
                'verbose_name_plural': 'Trading Signals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSignalPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_reference', models.CharField(max_length=50, unique=True)),
                ('signal_data', models.JSONField(help_text='Snapshot of signal data at purchase time')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_at', models.DateTimeField(auto_now=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='app.signal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signal Purchase',
                'verbose_name_plural': 'Signal Purchases',
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'signal')},
            },
        ),
    ]
