# Generated by Django 5.2.6 on 2025-11-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_next_amount_to_upgrade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country_calling_code',
            field=models.CharField(blank=True, help_text='Country phone code (e.g., +1, +234)', max_length=10, null=True),
        ),
    ]
