# Generated by Django 5.2.6 on 2025-09-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='This is a monetary value.', max_digits=20, verbose_name='Balance'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='equity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='This is a monetary value.', max_digits=20, verbose_name='Equity'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='free_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='This is a monetary value.', max_digits=20, verbose_name='Free Margin'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='margin_level',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The Margin Level is a Percentage value. It should range from 0% to 20%.', max_digits=20, verbose_name='Margin Level'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_funds',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='This is a monetary value.', max_digits=20, verbose_name='User Funds'),
        ),
    ]
