# Generated by Django 5.2.6 on 2025-11-06 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_country_calling_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('shares', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, help_text='Only for sell orders', max_digits=20, null=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='app.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trade History',
                'verbose_name_plural': 'Trade Histories',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['user', '-executed_at'], name='app_tradehi_user_id_b0d259_idx'), models.Index(fields=['stock', '-executed_at'], name='app_tradehi_stock_i_f2f514_idx')],
            },
        ),
    ]
