# Generated by Django 5.2.6 on 2025-11-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tradehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='priority',
        ),
    ]
