# Generated by Django 5.2.6 on 2025-11-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_notification_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='total_losses',
            field=models.PositiveIntegerField(default=0, help_text='Total number of losing trades'),
        ),
        migrations.AddField(
            model_name='trader',
            name='total_wins',
            field=models.PositiveIntegerField(default=0, help_text='Total number of winning trades'),
        ),
    ]
