# Generated by Django 5.2.6 on 2025-11-17 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_trader_total_losses_trader_total_wins'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTraderCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_actively_copying', models.BooleanField(default=True, help_text='Whether user is currently actively copying this trader')),
                ('minimum_amount_user_copied', models.DecimalField(decimal_places=2, help_text='Minimum threshold amount when user started copying', max_digits=12)),
                ('started_copying_at', models.DateTimeField(auto_now_add=True, help_text='When the user started copying this trader')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time the copy status was updated')),
                ('stopped_copying_at', models.DateTimeField(blank=True, help_text='When the user stopped copying (if applicable)', null=True)),
                ('trader', models.ForeignKey(help_text='Trader being copied', on_delete=django.db.models.deletion.CASCADE, related_name='copying_users', to='app.trader')),
                ('user', models.ForeignKey(help_text='User who is copying the trader', on_delete=django.db.models.deletion.CASCADE, related_name='copied_traders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Trader Copy',
                'verbose_name_plural': 'User Trader Copies',
                'ordering': ['-started_copying_at'],
                'indexes': [models.Index(fields=['user', 'trader', 'is_actively_copying'], name='app_usertra_user_id_348c56_idx'), models.Index(fields=['is_actively_copying'], name='app_usertra_is_acti_e708bb_idx')],
                'unique_together': {('user', 'trader')},
            },
        ),
    ]
