# Generated by Django 5.2.6 on 2025-11-27 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_usertradercopy'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCopyTraderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(help_text='Market/Asset name (e.g., BTC/USD, EUR/USD)', max_length=50)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], help_text='Trade direction: Buy or Sell', max_length=10)),
                ('leverage', models.CharField(help_text='Leverage used (e.g., 5x, 50x, 100x)', max_length=10)),
                ('duration', models.CharField(help_text='Trade duration (e.g., 2 minutes, 5 minutes, 1 hour)', max_length=50)),
                ('amount', models.DecimalField(decimal_places=8, help_text='Amount invested in base currency', max_digits=20)),
                ('entry_price', models.DecimalField(decimal_places=8, help_text='Entry price of the trade', max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, help_text='Exit price (for closed trades)', max_digits=20, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0.0, help_text='Profit or loss from this trade', max_digits=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', help_text='Trade status: Open or Closed', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True, help_text='When the trade was opened')),
                ('closed_at', models.DateTimeField(blank=True, help_text='When the trade was closed', null=True)),
                ('reference', models.CharField(help_text='Unique trade reference', max_length=100, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the trade', null=True)),
                ('trader', models.ForeignKey(help_text='Trader being copied', on_delete=django.db.models.deletion.CASCADE, related_name='copy_trade_history', to='app.trader')),
                ('user', models.ForeignKey(help_text='User who made this copy trade', on_delete=django.db.models.deletion.CASCADE, related_name='copy_trade_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Copy Trade History',
                'verbose_name_plural': 'Copy Trade Histories',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['user', '-opened_at'], name='app_usercop_user_id_4e972e_idx'), models.Index(fields=['trader', '-opened_at'], name='app_usercop_trader__205f90_idx'), models.Index(fields=['status'], name='app_usercop_status_cb6d64_idx')],
            },
        ),
    ]
