# Generated by Django 5.2.6 on 2025-09-30 14:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_ticket_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_back',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Back side of ID document', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_front',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Front side of ID document', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('driver_license', 'Driver’s License'), ('national_id', 'National ID'), ('voter_card', 'Voter’s Card')], help_text='Select the type of ID provided', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
