# Generated by Django 5.2.6 on 2025-12-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_usercopytraderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code_created_at',
            field=models.DateTimeField(blank=True, help_text='When the verification code was generated (expires in 10 minutes)', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Has user verified their email during signup?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Has user enabled 2FA for login?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(blank=True, help_text='4-digit verification code for email/2FA', max_length=4, null=True),
        ),
    ]
