# Generated by Django 5.2.6 on 2025-10-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_submitted_kyc',
            field=models.BooleanField(default=False),
        ),
    ]
