# Generated by Django 5.2.6 on 2025-10-01 11:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customuser_has_submitted_kyc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin (BTC)'), ('ETH', 'Ethereum (ETH)'), ('SOL', 'Solana (SOL)'), ('USDT', 'Tether (USDT)'), ('BNB', 'Binance Coin (BNB)'), ('TRX', 'Tron (TRX)')], max_length=10)),
                ('wallet_address', models.CharField(max_length=255, unique=True)),
                ('qr_code', cloudinary.models.CloudinaryField(blank=True, help_text='Optional QR code image for scanning', max_length=255, null=True, verbose_name='qr_code')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this payment option')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Wallet',
                'verbose_name_plural': 'Admin Wallets',
                'ordering': ['-created_at'],
            },
        ),
    ]
