# Generated by Django 5.2.6 on 2025-10-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_adminwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminwallet',
            name='currency',
            field=models.CharField(max_length=100),
        ),
    ]
