# Generated by Django 5.2.6 on 2025-10-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_adminwallet_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminwallet',
            name='currency',
            field=models.CharField(choices=[('BTC', 'Bitcoin (BTC)'), ('ETH', 'Ethereum (ETH)'), ('SOL', 'Solana (SOL)'), ('USDT', 'Tether (USDT)'), ('BNB', 'Binance Coin (BNB)'), ('TRX', 'Tron (TRX)')], max_length=100),
        ),
    ]
