# Generated by Django 5.2.6 on 2025-10-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_adminwallet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminwallet',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=12, verbose_name='Amount per unit'),
        ),
    ]
