# Generated by Django 5.2.6 on 2025-10-01 14:00

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_adminwallet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Here's the receipt for the transaction.", max_length=255, null=True, verbose_name='receipt'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='unit',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=12, verbose_name='Unit of currency'),
        ),
        migrations.AlterField(
            model_name='adminwallet',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional QR code image for scanning', max_length=255, null=True, verbose_name='QRCode'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount'),
        ),
    ]
