# Generated by Django 5.2.6 on 2025-10-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_transaction_currency_transaction_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminwallet',
            name='currency',
            field=models.CharField(choices=[('BTC', 'Bitcoin (BTC)'), ('ETH', 'Ethereum (ETH)'), ('SOL', 'Solana (SOL)'), ('USDT', 'Tether (USDT)'), ('BNB', 'Binance Coin (BNB)'), ('TRX', 'Tron (TRX)')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='adminwallet',
            name='wallet_address',
            field=models.CharField(max_length=255),
        ),
    ]
