# Generated by Django 5.2.6 on 2025-10-02 10:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_adminwallet_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload copy the trader image', max_length=255, null=True, verbose_name='Trader Image'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='avg_trade_time',
            field=models.CharField(help_text="This should be time basis like '1 week', '3 weeks', '2 months'", max_length=50),
        ),
        migrations.AlterField(
            model_name='trader',
            name='capital',
            field=models.CharField(help_text='Enter the amount in dollars e.g. 2000, 4000', max_length=50),
        ),
        migrations.AlterField(
            model_name='trader',
            name='copiers',
            field=models.PositiveIntegerField(help_text='This should range from 1 to 300 or even more.'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='gain',
            field=models.DecimalField(decimal_places=2, help_text='This should be the gain he made from the trade e.g. 194.32', max_digits=10),
        ),
        migrations.AlterField(
            model_name='trader',
            name='risk',
            field=models.PositiveSmallIntegerField(help_text='Risk score should be from 1 to 10.'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='trades',
            field=models.PositiveIntegerField(help_text='This should be an integer showing the number of trade this trader has taken.'),
        ),
    ]
