# Generated by Django 5.2.6 on 2025-10-02 23:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_trader_avatar_alter_trader_avg_trade_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Forex', 'Forex'), ('Crypto', 'Crypto'), ('Commodities', 'Commodities'), ('Stocks', 'Stocks')], help_text='Choose the asset category. Example: Forex, Crypto, Commodities, Stocks', max_length=20)),
                ('symbol', models.CharField(help_text='Enter the trading symbol. Example: EURUSD, BTCUSD, XAUUSD', max_length=20, unique=True)),
                ('flag', cloudinary.models.CloudinaryField(blank=True, help_text='Upload the asset flag/logo image. Example: eurousd_nobg.png', max_length=255, null=True, verbose_name='QRCode')),
                ('change', models.FloatField(help_text='Enter the percentage change in price. Example: 0.02 for +0.02%')),
                ('bid', models.DecimalField(decimal_places=6, help_text='Enter the bid price (buy). Example: 1.18031', max_digits=20)),
                ('ask', models.DecimalField(decimal_places=6, help_text='Enter the ask price (sell). Example: 1.18051', max_digits=20)),
                ('low', models.DecimalField(decimal_places=6, help_text='Enter the lowest price for the period. Example: 1.17626', max_digits=20)),
                ('high', models.DecimalField(decimal_places=6, help_text='Enter the highest price for the period. Example: 1.18199', max_digits=20)),
                ('time', models.TimeField(help_text='Enter the timestamp of the price update. Example: 10:47:52')),
            ],
        ),
        migrations.AlterModelOptions(
            name='trader',
            options={'verbose_name': 'Trader', 'verbose_name_plural': 'Copy Traders'},
        ),
    ]
