# Generated by Django 5.2.6 on 2025-10-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_asset_alter_trader_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminwallet',
            name='currency',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
