# Generated by Django 5.2.6 on 2025-10-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_adminwallet_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminwallet',
            name='currency',
            field=models.CharField(choices=[('BTC', 'Bitcoin (BTC)'), ('ETH', 'Ethereum (ETH)'), ('SOL', 'Solana (SOL)'), ('USDT', 'USDT (ERC20)'), ('BNB', 'Binance Coin (BNB)'), ('TRX', 'Tron (TRX)'), ('USDC', 'USDC (BASE)')], max_length=100, unique=True),
        ),
    ]
