# Generated by Django 5.2.6 on 2025-10-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_adminwallet_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminwallet',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=10.0, max_digits=20, verbose_name='Amount per unit'),
        ),
    ]
